/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;


import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Malaw
 */
public class Donneurs extends javax.swing.JFrame {

    /**
     * Creates new form Donneurs
     */
    public Donneurs() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        setSize(d.width, d.height);
        afficher();
    }
    
    public Connection getConnection(){
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:mysql://localhost/banquedesang", "root", "");
            return con;
        }
        catch(SQLException e){
            return null;
        }
    }
    
    public ArrayList<Donneur> getUserList(){
        ArrayList<Donneur> usersList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "SELECT * FROM donneur";
        Statement st;
        ResultSet rs;
        try{
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Donneur donneur;
            while(rs.next()){
                    donneur = new Donneur(rs.getString("idDonneur"), rs.getString("nomDonneur"), rs.getString("prenomDonneur"), rs.getInt("idGroupe"),rs.getString("adresse"), rs.getString("dateNaiss"), rs.getString("lieuNaiss"), rs.getInt("taille"), rs.getInt("poids"), rs.getString("genre"), rs.getInt("numTel"), rs.getInt("cin"), rs.getString("login"), rs.getString("password") );
                usersList.add(donneur);            
            }
        }
        catch(SQLException e){
        }
        return usersList;
    }
    
    public final void afficher(){
        ArrayList<Donneur> list = getUserList();
        DefaultTableModel model = (DefaultTableModel)listeDonneur.getModel();
        Object[] row = new Object[13];
        for(int i = 0; i < list.size(); i++){
            row[0] = i + 1;
            row[1] = list.get(i).getIdDonneur();
            row[2] = list.get(i).getPrenomDonneur();
            row[3] = list.get(i).getNomDonneur();
            row[4] = list.get(i).getIdGroupe();
            row[5] = list.get(i).getAdresse();
            row[6] = list.get(i).getDateNaiss();
            row[7] = list.get(i).getLieuNaiss();
            row[8] = list.get(i).getTaille();
            row[9] = list.get(i).getPoids();
            row[10] = list.get(i).getGenre();
            row[11] = list.get(i).getNumTel();
            row[12] = list.get(i).getCin();
            
            model.addRow(row); 
        }
    }
    
    public void executeSqlQuery(String query, String message){
        Connection con = getConnection();
        Statement st;
        try{
            st = con.createStatement();
            if(st.executeUpdate(query) ==1){
                DefaultTableModel model = (DefaultTableModel)listeDonneur.getModel();
                model.setRowCount(0);
                afficher();
                JOptionPane.showMessageDialog(null, "Donneur "+message+" avec succees");
            }
            else{
                JOptionPane.showMessageDialog(null, "Donneur non "+ message);
                
            }
        }
        catch(HeadlessException | SQLException ex){
           
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listeDonneur = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_nbrTotal = new javax.swing.JTextField();
        modifier = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        inscrire = new javax.swing.JButton();
        profil = new javax.swing.JButton();
        rechercher = new javax.swing.JButton();
        jTextField_Recherche = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_CIN = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox<>();
        welcomeBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Tel = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Poids = new javax.swing.JTextField();
        jTextField_Taille = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_lieuNaiss = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField_grpSanguin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_Prenom = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField_Nom = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dateNaiss = new datechooser.beans.DateChooserCombo();
        btnDeconnect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        listeDonneur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "N° donneur", "Prenom", "Nom", "Grp Sanguin", "Addresse", "DateNaiss", "LieuNaiss", "Taille", "Poids", "Genre", "Telephone", "CIN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, true, true, true, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listeDonneur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listeDonneurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listeDonneur);
        if (listeDonneur.getColumnModel().getColumnCount() > 0) {
            listeDonneur.getColumnModel().getColumn(0).setHeaderValue("N°");
            listeDonneur.getColumnModel().getColumn(1).setHeaderValue("N° donneur");
            listeDonneur.getColumnModel().getColumn(2).setHeaderValue("Prenom");
            listeDonneur.getColumnModel().getColumn(3).setHeaderValue("Nom");
            listeDonneur.getColumnModel().getColumn(4).setHeaderValue("Grp Sanguin");
            listeDonneur.getColumnModel().getColumn(5).setHeaderValue("Addresse");
            listeDonneur.getColumnModel().getColumn(6).setHeaderValue("DateNaiss");
            listeDonneur.getColumnModel().getColumn(7).setHeaderValue("LieuNaiss");
            listeDonneur.getColumnModel().getColumn(8).setHeaderValue("Taille");
            listeDonneur.getColumnModel().getColumn(9).setHeaderValue("Poids");
            listeDonneur.getColumnModel().getColumn(10).setHeaderValue("Genre");
            listeDonneur.getColumnModel().getColumn(11).setHeaderValue("Telephone");
            listeDonneur.getColumnModel().getColumn(12).setHeaderValue("CIN");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 0, 920, 550);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Total de donneurs: ");

        modifier.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        modifier.setText("Modifier");

        supprimer.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });

        actualiser.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        actualiser.setText("Actualiser");

        inscrire.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        inscrire.setText("Inscrire");
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });

        profil.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        profil.setText("Profil");

        rechercher.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        rechercher.setText("Rechercher");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(inscrire, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(modifier, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTextField_Recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(supprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profil, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(actualiser, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nbrTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(425, 425, 425)
                    .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(717, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(modifier, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(supprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(actualiser, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(inscrire, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .addComponent(jTextField_nbrTotal)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profil, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jTextField_Recherche))
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(rechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 560, 1320, 160);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel1.setText("CIN: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 510, 40, 30);

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Genre:  ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 440, 60, 20);

        jTextField_CIN.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_CIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_CINActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_CIN);
        jTextField_CIN.setBounds(180, 510, 210, 30);

        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        getContentPane().add(genre);
        genre.setBounds(180, 440, 50, 20);

        welcomeBtn.setText("Acceuil");
        welcomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                welcomeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(welcomeBtn);
        welcomeBtn.setBounds(10, 10, 110, 23);

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setText("Telephone:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 470, 70, 30);

        jTextField_Tel.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TelActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Tel);
        jTextField_Tel.setBounds(180, 470, 210, 30);

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setText("Poids:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(80, 400, 40, 30);

        jTextField_Poids.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Poids.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PoidsActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Poids);
        jTextField_Poids.setBounds(180, 400, 210, 30);

        jTextField_Taille.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Taille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_TailleActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Taille);
        jTextField_Taille.setBounds(180, 360, 210, 30);

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setText("Taille: ");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(80, 360, 60, 30);

        jTextField_lieuNaiss.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_lieuNaiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_lieuNaissActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_lieuNaiss);
        jTextField_lieuNaiss.setBounds(180, 320, 210, 30);

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setText("Lieu de Naiss: ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(30, 320, 100, 30);

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setText("Date de Naiss: ");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(30, 280, 100, 30);

        jTextField_Address.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_AddressActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Address);
        jTextField_Address.setBounds(180, 240, 210, 30);

        jLabel18.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel18.setText("Addresse:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 240, 70, 30);

        jTextField_grpSanguin.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_grpSanguin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_grpSanguinActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_grpSanguin);
        jTextField_grpSanguin.setBounds(180, 200, 210, 30);

        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setText("Groupe Sanguin:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(10, 200, 110, 30);

        jTextField_Prenom.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PrenomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Prenom);
        jTextField_Prenom.setBounds(180, 120, 210, 30);

        jLabel20.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel20.setText("Prenom:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(60, 120, 60, 30);

        jTextField_Nom.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jTextField_Nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NomActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Nom);
        jTextField_Nom.setBounds(180, 160, 210, 30);

        jLabel21.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel21.setText("Nom:");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(80, 160, 40, 30);

        jTextField_ID.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_ID);
        jTextField_ID.setBounds(180, 80, 210, 30);

        jLabel22.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel22.setText("N° Donneur: ");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 80, 90, 30);
        getContentPane().add(dateNaiss);
        dateNaiss.setBounds(180, 280, 210, 30);

        btnDeconnect.setText("Deconnecter");
        btnDeconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeconnectActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeconnect);
        btnDeconnect.setBounds(150, 10, 100, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_CINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_CINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_CINActionPerformed

    private void welcomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_welcomeBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        sgbs.Welcome wel = new sgbs.Welcome();
        wel.setVisible(true);
    }//GEN-LAST:event_welcomeBtnActionPerformed

    private void jTextField_TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TelActionPerformed

    private void jTextField_PoidsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PoidsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PoidsActionPerformed

    private void jTextField_TailleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_TailleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TailleActionPerformed

    private void jTextField_lieuNaissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_lieuNaissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_lieuNaissActionPerformed

    private void jTextField_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_AddressActionPerformed

    private void jTextField_grpSanguinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_grpSanguinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_grpSanguinActionPerformed

    private void jTextField_PrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PrenomActionPerformed

    private void jTextField_NomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NomActionPerformed

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
        // TODO add your handling code here:
        String query = "INSERT into stock ( ID, dateStock, dateExp, grpSanguin) VALUES ('"+jTextField_ID.getText()+"','"+jTextField_Prenom.getText()+"', '"+jTextField_Nom.getText()+"', '"+jTextField_grpSanguin.getText()+"','"+jTextField_Address.getText()+"','"+dateNaiss.getText()+"','"+jTextField_lieuNaiss.getText()+"','"+jTextField_Taille.getText()+"','"+jTextField_Poids.getText()+"','"+genre.getSelectedItem()+"','"+jTextField_Tel.getText()+"','"+jTextField_CIN.getText()+"')";
        executeSqlQuery(query, "inscrit");
    }//GEN-LAST:event_inscrireActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        String query = "DELETE from donneur where id = '"+jTextField_ID.getText()+"'";
        executeSqlQuery(query, "supprimés");
    }//GEN-LAST:event_supprimerActionPerformed

    private void listeDonneurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listeDonneurMouseClicked
        // TODO add your handling code here:
        int i = listeDonneur.getSelectedRow();
        TableModel model = listeDonneur.getModel();
        
        jTextField_ID.setText(model.getValueAt(i, 1).toString());
        jTextField_Prenom.setText(model.getValueAt(i, 2).toString());
        jTextField_Nom.setText(model.getValueAt(i, 3).toString());
        jTextField_grpSanguin.setText(model.getValueAt(i, 4).toString());
        jTextField_Address.setText(model.getValueAt(i, 5).toString());
        dateNaiss.setText(model.getValueAt(i, 6).toString());
        jTextField_lieuNaiss.setText(model.getValueAt(i, 7).toString());
        jTextField_Taille.setText(model.getValueAt(i, 8).toString());
        jTextField_Poids.setText(model.getValueAt(i, 9).toString());
        jTextField_Tel.setText(model.getValueAt(i, 11).toString());
        jTextField_CIN.setText(model.getValueAt(i, 12).toString());
        
    }//GEN-LAST:event_listeDonneurMouseClicked
    
    private JFrame frame;
    private void btnDeconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeconnectActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Quitter");
        if(JOptionPane.showConfirmDialog(frame, "Voulez-vous vraiment quitter l'application?", "Deconnexion ", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION ){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnDeconnectActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiser;
    private javax.swing.JButton btnDeconnect;
    private datechooser.beans.DateChooserCombo dateNaiss;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JButton inscrire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_CIN;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Nom;
    private javax.swing.JTextField jTextField_Poids;
    private javax.swing.JTextField jTextField_Prenom;
    private javax.swing.JTextField jTextField_Recherche;
    private javax.swing.JTextField jTextField_Taille;
    private javax.swing.JTextField jTextField_Tel;
    private javax.swing.JTextField jTextField_grpSanguin;
    private javax.swing.JTextField jTextField_lieuNaiss;
    private javax.swing.JTextField jTextField_nbrTotal;
    private javax.swing.JTable listeDonneur;
    private javax.swing.JButton modifier;
    private javax.swing.JButton profil;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton supprimer;
    private javax.swing.JButton welcomeBtn;
    // End of variables declaration//GEN-END:variables
}
