/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgbs;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utils.Don;
import utils.Donneurs;

/**
 *
 * @author Malaw
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        setSize(d.width, d.height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donneurBtn = new javax.swing.JButton();
        stockBtn = new javax.swing.JButton();
        statsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnDon = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        rvBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        donneurBtn.setText("Donneurs");
        donneurBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donneurBtnActionPerformed(evt);
            }
        });
        getContentPane().add(donneurBtn);
        donneurBtn.setBounds(890, 130, 192, 36);

        stockBtn.setText("Stocks");
        stockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBtnActionPerformed(evt);
            }
        });
        getContentPane().add(stockBtn);
        stockBtn.setBounds(890, 200, 192, 38);

        statsBtn.setText("Stats");
        getContentPane().add(statsBtn);
        statsBtn.setBounds(890, 400, 192, 38);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/morristown-csd-blood-drive-15-728.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 30, 770, 570);

        btnDon.setText("Don");
        btnDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonActionPerformed(evt);
            }
        });
        getContentPane().add(btnDon);
        btnDon.setBounds(890, 270, 192, 38);

        quitBtn.setText("Quitter");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quitBtn);
        quitBtn.setBounds(890, 470, 192, 38);

        rvBtn.setText("Rendez-vous");
        getContentPane().add(rvBtn);
        rvBtn.setBounds(890, 340, 192, 38);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void donneurBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donneurBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        utils.MenuDonneur md = new utils.MenuDonneur();
        md.setVisible(true);
        
    }//GEN-LAST:event_donneurBtnActionPerformed

    private void stockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        utils.Stocks st = new utils.Stocks();
        st.setVisible(true);
    }//GEN-LAST:event_stockBtnActionPerformed

    private void btnDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonActionPerformed
        // TODO add your handling code here:
        dispose();
        Don don = new Don();
        don.setVisible(true);
        
    }//GEN-LAST:event_btnDonActionPerformed
    
    JFrame frame;
    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Quitter");
        if(JOptionPane.showConfirmDialog(frame, "Voulez-vous vraiment quitter l'application?", "Deconnexion ", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION ){
            System.exit(0);
        }
    }//GEN-LAST:event_quitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDon;
    private javax.swing.JButton donneurBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton rvBtn;
    private javax.swing.JButton statsBtn;
    private javax.swing.JButton stockBtn;
    // End of variables declaration//GEN-END:variables
}
